export const SET_COUNTRY_STATISTICS = 'SET_COUNTRY_STATISTICS';
export const SET_DATE_RANGE = 'SET_DATE_RANGE';
export const SET_SELECTED_DATE = 'SET_SELECTED_DATE';
export const SET_TOOLTIP_DATA = 'SET_TOOLTIP_DATA';
export const RESET_TOOLTIP_DATA = 'RESET_TOOLTIP_DATA';
export const SET_WINDOW_SIZE = 'SET_WINDOW_SIZE';
export const SET_GLOBAL_STATISTIC = 'SET_GLOBAL_STATISTIC';
